# Generated by Django 2.0.4 on 2018-05-03 18:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nl', models.TextField(help_text='A natural language description of a bash command.', max_length=300, null=True, verbose_name='Natural Language Command')),
                ('bash', models.TextField(help_text='A bash command.', max_length=300, null=True, verbose_name='Bash Command')),
            ],
        ),
        migrations.CreateModel(
            name='CommandPairInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cmd_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nl2bash_server_app.CommandPair')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True, verbose_name='Verification Score')),
            ],
        ),
        migrations.AddField(
            model_name='commandpair',
            name='ver_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nl2bash_server_app.Verification'),
        ),
    ]
