# Generated by Django 2.0.5 on 2018-05-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nl2bash_server_app', '0002_auto_20180504_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandpair',
            name='saved_status',
            field=models.BooleanField(default=0, verbose_name='Saved'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='score',
            field=models.IntegerField(default=0, null=True, verbose_name='Verification Score'),
        ),
    ]
